features/Users-CRUD
sergiuchilat/bitsoft-auth-provider pull request #14
Opened 2024-05-18 12:24 UTC by Vicu1

2024-05-18 12:35 UTC, sergiuchilat requested changes

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +        lang: 'en',
language must be from l-localization header || "en"

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +      throw e;
Did you test this? Api must return a readable error. In case of error, user must see what happens

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +        throw new HttpException ('Invalid token', HttpStatus.NOT_FOUND);
add localization

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +      throw new HttpException ('Error activate user', HttpStatus.CONFLICT);
add localization

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/dto/classic-auth-activate-resend.payload.dto.ts
> +  @ApiProperty ({ example: 'mail@domain.com', description: 'Email' })
add @IsEmail()

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/users/dto/user-item.response.dto.ts
> +    @Expose()
add @IsEmail()

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/users/users.repository.ts
> +  async findAndCountAll (pageOptionsDto: PageOptionsDto): Promise<[UserEntity[], number]> {
rename to findAllAndCount

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/users/users.repository.ts
> +    return [entities, count];
wrong response format for paginated response

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/users/users.repository.ts
> +      throw new NotFoundException(`User with uuid: ${uuid} not found!`);
localization

2024-05-18 12:35 UTC, sergiuchilat commented on src/app/modules/users/users.repository.ts
> +      throw new NotFoundException(`User with uuid: ${uuid} not found!`);
localization

2024-05-28 10:50 UTC, sergiuchilat requested changes

2024-05-28 10:50 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.controller.ts
> +      .send (await this.classicAuthService.resendActivationEmail(classicAuthActivateResendPayloadDto, request));
Is not necessary to pass all request object. Pass just a part of request that you need

2024-05-28 10:50 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.controller.ts
> +      .send (await this.classicAuthService.activate (token, request));
do not pass all request object, pass just a part that you need

2024-05-28 10:50 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +    const message = {
Wrong implementation. Language must be extracted from a header in a middleware and be injected here

2024-05-28 10:50 UTC, sergiuchilat commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +    const message = {
src/app/middleware/middlewares/parse-localization.middleware.ts

2024-05-28 10:50 UTC, sergiuchilat commented on src/app/modules/users/users.repository.ts
> +          lang: request.headers['l-localization'] || 'en',
wrong implementation. x-localization not l-localization. use localization middleware

2024-06-11 12:33 UTC, Vady4ek requested changes

2024-06-11 12:33 UTC, Vady4ek commented on src/app/middleware/index.ts
> +import {ParseLocalizationMiddleware} from '@/app/middleware/middlewares/parse-localization.middleware';
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/auth/classic-auth/classic-auth.module.ts
> +  providers: [ClassicAuthService, UsersService, JwtService, MailerService, UsersRepository],
Export providers from module

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/auth/classic-auth/classic-auth.controller.ts
> +  async resendActivationEmail (
Remove async

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +import {Language} from '@/app/enum/language.enum';
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
> +    private readonly i18n: I18nService,
Rename to i18nService, since all services ends with service in this project

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/auth/classic-auth/classic-auth.service.ts
>      // await this.classicAuthRepository.delete ({
Remove comments

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.module.ts
> +import {UsersRepository} from '@/app/modules/users/users.repository';
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.module.ts
> +  providers: [UsersService, UsersRepository],
Export providers

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.repository.ts
> +import {Language} from '@/app/enum/language.enum';
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.repository.ts
> +  constructor(private readonly dataSource: DataSource,
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.repository.ts
> +  async block (uuid: string)  {
Remove async

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.repository.ts
> +  async unblock (uuid: string)  {
Remove async

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.service.ts
> +import {Language} from '@/app/enum/language.enum';
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.service.ts
> +      private readonly entityManager: EntityManager
Format with prettier

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.service.ts
Renive async/await for all this methods, since you just return promise here.
https://eslint.org/docs/latest/rules/no-return-await

2024-06-11 12:33 UTC, Vady4ek commented on src/app/modules/users/users.service.ts
> +    email: string = null,
email: string | null = null

2024-06-14 13:00 UTC, Vady4ek approved these changes

2024-06-14 13:01 UTC, merged